[package]
name = "app"
description = "Lepo GitHub repo monitor - Leptos CSR front-end."
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[[bin]]
name = "app"
path = "src/main.rs"

[dependencies]
models.workspace = true
github-api.workspace = true

leptos.workspace = true
leptos_router.workspace = true
gloo-net.workspace = true
gloo-storage.workspace = true
gloo-timers.workspace = true
tracing.workspace = true
tracing-wasm.workspace = true
console_error_panic_hook.workspace = true
web-sys.workspace = true
js-sys.workspace = true
chrono.workspace = true
thiserror.workspace = true
serde.workspace = true
futures.workspace = true
